#!/usr/bin/env python3
"""
gen_esw_banks.py — Convert Echo Sound Works Core Tables → ESWWavetables.h
Reads all WAVs, resamples to 2048 samples, normalises, outputs C++ header.
Banks with >16 files are split into numbered groups.
"""
import os, sys, glob, math
import numpy as np
import soundfile as sf

WT_SIZE    = 2048
MAX_FRAMES = 16   # max waveforms per bank before splitting

SRC_DIR = os.path.expanduser("~/Downloads/Echo Sound Works Core Tables")
OUT_H   = os.path.join(os.path.dirname(__file__), "../Source/engine/oscillators/ESWWavetables.h")

# Colour palette per category (ARGB hex)
CATEGORY_COLOURS = {
    "Analog":        "0xFFFF7043",   # deep orange
    "Basics":        "0xFF4FC3F7",   # sky blue
    "Chill":         "0xFF80CBC4",   # teal
    "Digital":       "0xFFCE93D8",   # purple
    "FM":            "0xFFFFD740",   # amber
    "Growl":         "0xFFEF5350",   # red
    "Instruments":   "0xFF66BB6A",   # green
    "Metallic":      "0xFFB0BEC5",   # silver
    "Spectral":      "0xFF40C4FF",   # cyan
    "Synth One Shots":"0xFFFF80AB",  # pink
    "Vocal":         "0xFFFFA726",   # orange-amber
}

def resample_to_wt(samples: np.ndarray) -> np.ndarray:
    """Resample to WT_SIZE samples using linear interpolation, then normalise."""
    n = len(samples)
    if n == WT_SIZE:
        out = samples.astype(np.float32)
    else:
        x_old = np.linspace(0, 1, n, endpoint=False)
        x_new = np.linspace(0, 1, WT_SIZE, endpoint=False)
        out   = np.interp(x_new, x_old, samples).astype(np.float32)
    # Normalise to ±1
    peak = np.max(np.abs(out))
    if peak > 1e-6:
        out /= peak
    return out

def format_float_array(arr: np.ndarray, indent="    ") -> str:
    chunks = []
    for i in range(0, len(arr), 16):
        row = arr[i:i+16]
        chunks.append(indent + ", ".join(f"{v:.6f}f" for v in row))
    return ",\n".join(chunks)

def main():
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    # Collect all categories
    categories = sorted([d for d in os.listdir(SRC_DIR)
                         if os.path.isdir(os.path.join(SRC_DIR, d))])

    banks = []  # list of dicts: name, colour, frames (list of np arrays)

    for cat in categories:
        cat_dir  = os.path.join(SRC_DIR, cat)
        wavs     = sorted(glob.glob(os.path.join(cat_dir, "*.wav")) +
                          glob.glob(os.path.join(cat_dir, "*.WAV")))
        colour   = CATEGORY_COLOURS.get(cat, "0xFF4FC3F7")

        # Split into groups of MAX_FRAMES
        num_groups = math.ceil(len(wavs) / MAX_FRAMES)
        for g in range(num_groups):
            group_wavs = wavs[g * MAX_FRAMES : (g + 1) * MAX_FRAMES]
            name = cat if num_groups == 1 else f"{cat} {g+1}"
            frames = []
            for wav_path in group_wavs:
                try:
                    data, _ = sf.read(wav_path, always_2d=False)
                    if data.ndim > 1:
                        data = data[:, 0]
                    frames.append(resample_to_wt(data))
                    print(f"  ✓ {os.path.basename(wav_path)}")
                except Exception as e:
                    print(f"  ✗ {os.path.basename(wav_path)}: {e}", file=sys.stderr)
            if frames:
                banks.append({"name": name, "colour": colour, "frames": frames})

    # Generate header
    lines = []
    lines.append("// AUTO-GENERATED by scripts/gen_esw_banks.py — DO NOT EDIT")
    lines.append("// Echo Sound Works Core Tables — built-in wavetable banks")
    lines.append("#pragma once")
    lines.append("#include <array>")
    lines.append("")
    lines.append(f"static constexpr int kESWBankCount  = {len(banks)};")
    lines.append(f"static constexpr int kESWWTSize      = {WT_SIZE};")
    lines.append("")

    # Emit frame data arrays
    for bi, bank in enumerate(banks):
        safe_name = bank["name"].replace(" ", "_").replace("/", "_")
        lines.append(f"// ── Bank {bi}: {bank['name']} ({''+str(len(bank['frames']))} frames) ──")
        for fi, frame in enumerate(bank["frames"]):
            lines.append(f"static constexpr float kESW_{safe_name}_F{fi}[{WT_SIZE}] = {{")
            lines.append(format_float_array(frame))
            lines.append("};")
        lines.append("")

    # Struct describing each bank
    lines.append("struct ESWBankDef {")
    lines.append("    const char* name;")
    lines.append("    uint32_t    colour;")
    lines.append("    int         numFrames;")
    lines.append(f"    const float* frames[{MAX_FRAMES}];")
    lines.append("};")
    lines.append("")
    lines.append(f"static const ESWBankDef kESWBanks[kESWBankCount] = {{")
    for bi, bank in enumerate(banks):
        safe_name = bank["name"].replace(" ", "_").replace("/", "_")
        nf        = len(bank["frames"])
        ptrs      = ", ".join(f"kESW_{safe_name}_F{fi}" for fi in range(nf))
        # Pad to MAX_FRAMES with nullptr
        if nf < MAX_FRAMES:
            ptrs += ", " + ", ".join("nullptr" * (MAX_FRAMES - nf)).replace("nullptr*", "nullptr")
            # fix the above
            ptrs = ", ".join([f"kESW_{safe_name}_F{fi}" for fi in range(nf)] +
                             ["nullptr"] * (MAX_FRAMES - nf))
        lines.append(f'    {{ "{bank["name"]}", {bank["colour"]}, {nf}, {{ {ptrs} }} }},')
    lines.append("};")
    lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines) + "\n")

    total_frames = sum(len(b["frames"]) for b in banks)
    print(f"\n✅  {len(banks)} banks, {total_frames} frames → {OUT_H}")

if __name__ == "__main__":
    main()
